# Generated by Django 4.1.1 on 2022-10-28 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=2048)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CACertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=2048)),
                ('allow_issue', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=1024)),
                ('private_key_algorithm', models.CharField(max_length=100)),
                ('private_key', models.BinaryField(default=b'', max_length=4096)),
                ('certificate', models.BinaryField(default=b'', max_length=51200)),
                ('certification_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camanager.certificationauthority')),
                ('issued_by_certificate', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='camanager.cacertificate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
