# Generated by Django 4.1.1 on 2022-10-27 08:15

from django.db import migrations
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.conf import settings
from django.utils import timezone


def create_default_admin(apps, schema_editor):
    user = get_user_model().objects.create_user(username = 'admin', email = 'admin@example.com', password = 'setup', last_login = timezone.now())

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_default_admin)
    ]
